spring:
  profiles:
    active: local
  application:
    name: rhf-service
  redis:
    host: redis://49.235.66.54:6379
    password: rhf1028623847
  rabbitmq:
    port: 5672
    host: 49.235.66.54
    username: guest
    password: guest
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: test
    #这个配置是保证消费者会消费消息，手动确认
    listener:
      direct:
        acknowledge-mode: manual
    template:
      mandatory: true
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://49.235.66.54:3306/lqq?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC+8
          username: root
          password: rhf1028623847
        #slave:
          #url: jdbc:mysql://weee.db.tb1.sayweee.net:3306/weee_comm?characterEncoding=UTF-8&allowMultiQueries=true
          #username: weee_customer
          #password: JcYuU8JLzly4457b
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

project:
  base-package-prefix: com.example.demo

xxl:
  job:
    admin:
      ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      #addresses: http://49.235.66.54:9999/xxl-job-admin
      addresses: http://localhost:10001/xxl-job-admin
    ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken:
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: rhf-service
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9998
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30


# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: xc_satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

#微信小程序配置
wx:
  miniapp:
    configs:
      - appid: wx450deaebd60a5048
        secret: 6cdf96956424fc8ea215000547262cc2
        token: 33
        aesKey: 44
        msgDataFormat: JSON

user:
  login:
    salt: uuuiiidd